project_id = "zcrnfrijqasbrjrxconi"

[functions.prerender-story]
verify_jwt = false

[functions.prerender-post]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.prerender-marketing]
verify_jwt = false
